name: CI
on: push

jobs:
  lint:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "::set-output name=dir::$(pnpm store path)"
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-      
      - name: Install Dependencies
        run: pnpm install
      - name: Run Format
        run: pnpm format
  typecheck:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "::set-output name=dir::$(pnpm store path)"
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-      
      - name: Install Dependencies
        run: pnpm install
      - run: pnpm build
